### ISSUE TITLE
Issues with OS X 10.10.2 beta?

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-studio-classic#1119]
My Mapbox Studio (v0.2.0) has stopped uploading and exporting source data files: direct upload gets to 100% but never reports completion and exporting asks for a download location but never creates the .mbtiles file. I've not had the issue previously but am using the latest 10.10.2 developer beta - could this be the cause? Nothing is written into the app log.

**Comment by mtirwin** [comment]
Download bug being addressed at #944.

**Comment by mtirwin** [comment]
Scratch that – looks like this is entirely a duplicate of #944.

**Comment by ashleyclough** [comment]
It's not quite the same - running studio in the browser does at least allow me to export the mbtiles but it still fails with direct uploading.

**Comment by ashleyclough** [comment]
It turns out it had been failing on upload processing because of too much data - your new data page that hides the history behind the upload button instead of the previous inline view had not allowed me to see the error. Even so, I had to manually delete the project reference in the data.yml in order to provoke a clean upload - reusing the previous reference after the initial fail resulted in no report of either success or failure in the upload window.

**Comment by willwhite** [comment]
Thanks, those details are very helpful.

> your new data page that hides the history behind the upload button instead of the previous inline view had not allowed me to see the error.

We are working to fix this on the mapbox.com side and are [considering making this information available in Mapbox Studio directly](https://github.com/mapbox/mapbox-studio/issues/1120) as well.

> Even so, I had to manually delete the project reference in the data.yml in order to provoke a clean upload - reusing the previous reference after the initial fail resulted in no report of either success or failure in the upload window.

I believe there is an Mapbox API error that is preventing you from re-using an id that previously errored. This is not intended and I'll look into fixing. [This issue](https://github.com/mapbox/mapbox-studio/issues/1081) is likely masking that error, which makes it more elusive.

I will update with more information soon.
